[config]

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell-colors.json"
output_path = "~/.config/quickshell/Theme/colors.json"

[templates.hyprcolors]
input_path = "~/.config/matugen/templates/hypr-colors.lua"
output_path = "~/.cache/matugen/hypr-colors.lua"
post_hook = "hyprctl reload"
