wallpaper {
    monitor = DP-3 
    path = ~/photos/wallpapers/red-orange-space.png
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1 
    path = ~/photos/wallpapers/red-orange-space.png
    fit_mode = cover
}
