preload = /home/iris/photos/wallpapers/red-orange-space.png
wallpaper = DP-3,/home/iris/photos/wallpapers/red-orange-space.png
wallpaper = HDMI-A-1,/home/iris/photos/wallpapers/red-orange-space.png
splash = false
